# -*- coding: utf-8 -*-
"""Training_Mob_Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klDrpWHje0YstaU_sl8TsyTKX7LZrm_K
"""

import pandas as pd
import csv
import numpy as np
from google.colab import files
uploaded = files.upload()
df2 = pd.read_csv('Training_Mob_Bot.csv')

with open("Training_Mob_Bot.csv", 'r') as f:
  data = list(csv.reader(f, delimiter=","))

data = np.array(data[1:], dtype=np.float)
#print(data)


S_Train=np.array([item[0] for item in data])
S_Train=(S_Train*1/max(S_Train))
Vl_Train=np.array([item[1] for item in data])
Vr_Train=np.array([item[2] for item in data])

A_Train = np.hstack([np.ones((S_Train.shape[0], 1)), S_Train.reshape(-1, 1), (S_Train**2).reshape(-1, 1)])
w_l=(np.linalg.inv(A_Train.T.dot(A_Train))).dot(A_Train.T.dot(Vl_Train)) 
#print(A_Train)
print(w_l)
w_r=(np.linalg.inv(A_Train.T.dot(A_Train))).dot(A_Train.T.dot(Vr_Train)) 
print(w_r)

A_Vl=[]
D=w_l.shape[0]
for i in S_Train:
  l=[]
  for j in range(D):
    l.append(i**j)
    A_Vl.append(l)
A_Vl= np.asarray(A_Vl)
Vl_P=A_Vl.dot(w_l)
#print(Vl_P)

